### ISSUE TITLE
请问docker运行后只提醒Now you can exit this program ! Good luck. 而不刷课怎么办

### ISSUE THREAD

**Issue by 19819068211** [luooofan/autochaoxing#23]
请问docker运行后只提醒Now you can exit this program ! Good luck. 而不刷课怎么办
![Screenshot_20210424_194116_com sonelli juicessh](https://user-images.githubusercontent.com/66981884/115957602-0673c700-a536-11eb-9d31-75a582aa5d5f.jpg)

**Comment by Luoofan** [comment]
后台应该已经在运行
`ps -aux | grep python3` 可以查看
