### ISSUE TITLE
Singlecourse.py修正

### ISSUE THREAD

**Issue by Helloat123** [luooofan/autochaoxing#25]
106行处，可能一个单元存在多节课，多个clearfix（在我刷课过程中遇到了只自动刷每个单元第一节课的情况）
我的改正方式是将106行改成
items=unit.find_all(class_='clearfix')
            for item in items:
两行
即可正常运行

**Comment by luooofan** [comment]
如果测试成功，可以提交pr。我这儿没有账号测试。
